server:
  port: 8080
  servlet:
    session:
      cookie:
        name: UISESSION
spring:
  thymeleaf:
    cache: false
  security:
    oauth2:
      client:
        registration:
          custom-client:
            client-id: client-app-1
            client-secret: 71CA90701F8EA396CB510883CC93454FC425F1C7F7A17B1487D751A7B5BF1173
            client-name: Auth Server
            scope: read
            provider: custom-provider
            redirect-uri: http://localhost:8080/login/oauth2/code/custom-client
            client-authentication-method: basic
            authorization-grant-type: authorization_code
        provider:
          custom-provider:
            token-uri: http://localhost:9000/oauth/token
            authorization-uri: http://localhost:9000/oauth/authorize
            user-info-uri: http://localhost:9000/api/user/me
            user-name-attribute: name